# https://github.com/golangci/golangci/wiki/Configuration
run:
  skip-dirs:
    - pkg/client
    - vendor
    - ui
  skip-files:
    - server/static/files.go
  build-tags:
    - e2e
    - cli
    - e2emc
linters:
  enable:
    - goimports
linters-settings:
  goimports:
    local-prefixes: github.com/argoproj/argo/
