apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: resource2-
spec:
  podGC:
    strategy: OnWorkflowCompletion
  entrypoint: main
  templates:
  - name: main
    dag:
      tasks:
        - name: deploy
          template: deploy
        - name: svc
          template: svc
          dependencies:
            - deploy
        - name: curl
          template: curl
          dependencies:
            - svc
        - name: sleep
          template: sleep
  - name: deploy
    resource2:
      apiVersion: apps/v1
      kind: Deployment
      spec:
        selector:
          matchLabels:
            app: hello
        template:
          metadata:
            labels:
              app: hello
              workflows.argoproj.io/workflows: "{{workflow.name}}"
          spec:
            containers:
              - name: main
                image: argoproj/argosay:v2
                args:
                  - server
                ports:
                  - name: http
                    containerPort: 8080
                readinessProbe:
                  httpGet:
                    port: 8080
  - name: svc
    resource2:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{workflow.name}}-svc"
      spec:
        ports:
          - name: http
            port: 8080
        selector:
          app: hello

  - name: curl
    container:
      image: argoproj/argosay:v2
      args:
        - http
        - get
        - "http://{{workflow.name}}-svc:8080"

  - name: sleep
    container:
      image: argoproj/argosay:v2
      args:
        - sleep
        - 3m
